global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
    metrics_path: '/metrics'

  - job_name: 'music-service'
    static_configs:
      - targets: ['music-service:3003']
    metrics_path: '/metrics'

  - job_name: 'streaming-service'
    static_configs:
      - targets: ['streaming-service:3004']
    metrics_path: '/metrics'

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:3005']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
