apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: spotify-clone
data:
  # Service URLs (internal cluster DNS)
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  MUSIC_SERVICE_URL: "http://music-service:3003"
  STREAMING_SERVICE_URL: "http://streaming-service:3004"
  SEARCH_SERVICE_URL: "http://search-service:3005"
  
  # Observability
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
  
  # Service Names
  SERVICE_NAME_AUTH: "auth-service"
  SERVICE_NAME_USER: "user-service"
  SERVICE_NAME_MUSIC: "music-service"
  SERVICE_NAME_STREAMING: "streaming-service"
  SERVICE_NAME_SEARCH: "search-service"
